kind: Namespace
apiVersion: v1
metadata:
  name: sw-factory
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
    - kubernetes
---
kind: Namespace
apiVersion: v1
metadata:
  name: vault
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
    - kubernetes