# Quay Registry Features
ocp4_workload_quay_operator_registry_enable_clair: true
ocp4_workload_quay_operator_registry_enable_hpa: false
ocp4_workload_quay_operator_registry_enable_mirror: false
ocp4_workload_quay_operator_registry_enable_monitoring: false

# ---------------------------------------
# Internal variables. Don't set or change
# ---------------------------------------
_quay_registry_route: ""
_quay_registry_admin_token: ""
