apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault-config-operator
  namespace: vault-config-operator
spec:
  channel: alpha 
  installPlanApproval: Automatic
  name: vault-config-operator 
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
  